// Copyright © 2020-2026 Petr Panteleyev
// SPDX-License-Identifier: BSD-2-Clause
package org.panteleyev.jpackage;

/**
 * Defines options for image generated by {@code jpackage} via {@code --type} option.
 */
public enum ImageType implements EnumParameter {
    /**
     * --type app-image
     */
    APP_IMAGE("app-image"),
    /**
     * --type dmg
     */
    DMG("dmg"),
    /**
     * --type pkg
     */
    PKG("pkg"),
    /**
     * --type exe
     */
    EXE("exe"),
    /**
     * --type msi
     */
    MSI("msi"),
    /**
     * --type rpm
     */
    RPM("rpm"),
    /**
     * --type deb
     */
    DEB("deb");

    private final String value;

    ImageType(String value) {
        this.value = value;
    }

    @Override
    public String getValue() {
        return value;
    }
}
